xl2tpd: support uci config

diff --git a/net/xl2tpd/files/xl2tpd.init b/net/xl2tpd/files/xl2tpd.init
--- a/net/xl2tpd/files/xl2tpd.init
+++ b/net/xl2tpd/files/xl2tpd.init
@@ -8,12 +8,92 @@ BIN=xl2tpd
 RUN_D="/var/run/xl2tpd"
 PID_F="/var/run/xl2tpd.pid"
 
+CONFIG=/var/etc/xl2tpd.conf
+CHAP_SECRETS=/var/etc/chap-secrets
+OPTIONS_XL2TPD=/var/etc/options.xl2tpd
+
+validate_login_section() {
+	uci_load_validate xl2tpd login "$1" "$2" \
+		'username:string' \
+		'password:string' \
+		'remoteip:string'
+}
+
+validate_xl2tpd_section() {
+	uci_load_validate xl2tpd service "$1" "$2" \
+		'enabled:uinteger' \
+		'localip:string' \
+		'remoteip:string'
+}
+
+setup_login() {
+	[ "$2" = 0 ] || {
+		echo "validation failed"
+		return 1
+	}
+
+	[ -n "$username" ] || return 0
+	[ -n "$password" ] || return 0
+	[ -n "$remoteip" ] || remoteip=*
+
+	echo "$username l2tp-server \"$password\" $remoteip" >> $CHAP_SECRETS.l2tp
+}
+
+setup_config() {
+	rm -f $CONFIG
+	[ "$2" = 0 ] || {
+		echo "validation failed, fallback default"
+		return 0
+	}
+
+	[ "$enabled" -eq 0 ] && {
+		return 0
+	}
+
+	mkdir -p /var/etc
+cat > $CONFIG <<-EOF
+[global]
+	port = 1701
+	;debug avp = yes
+	;debug network = yes
+	;debug state = yes
+	;debug tunnel = yes
+
+[lns default]
+	ip range = $remoteip
+	local ip = $localip
+	require chap = yes
+	refuse pap = yes
+	require authentication = no
+	name = l2tp-server
+	;ppp debug = yes
+	pppoptfile = $OPTIONS_XL2TPD
+	length bit = yes
+EOF
+	cat /etc/ppp/options.xl2tpd >$OPTIONS_XL2TPD
+	echo "ms-dns $localip" >>$OPTIONS_XL2TPD
+
+	return 0
+}
+
 start_service() {
+	config_load xl2tpd
+	validate_xl2tpd_section xl2tpd setup_config || return
+	:>$CHAP_SECRETS.l2tp
+	config_foreach validate_login_section login setup_login
+	cat $CHAP_SECRETS.pptp $CHAP_SECRETS.l2tp >$CHAP_SECRETS 2>/dev/null
+
+	ln -sn $CHAP_SECRETS /etc/ppp/chap-secrets &>/dev/null
+
 	rm -rf "$RUN_D"
 	mkdir -p "$RUN_D"
 
 	procd_open_instance
-	procd_set_param command $BIN -D -l -p "$PID_F"
+	if test -e $CONFIG; then
+		procd_set_param command $BIN -D -l -p "$PID_F" -c "$CONFIG"
+	else
+		procd_set_param command $BIN -D -l -p "$PID_F"
+	fi
 	procd_set_param respawn
 	procd_close_instance
 }
